# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: scheduled-table-generator

on:
  schedule:
      - cron: '0 22 * * *'  

jobs:

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run conformance table generator
      run: |
        cd conformance_table_generator/
        go run main.go -t phase2 -v 2
    
    - name: Run export data
      run: |
        cd ../export_data
        go run main.go -t phase2 -v 2
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: conformance table routine - ${{ steps.date.outputs.date }}
        title: conformance table routine - ${{ steps.date.outputs.date }}
        branch: table-routine
        delete-branch: true
        #team-reviewers: Raidiam
  
